# Run trufflehog at each commit and when merging to main.
# Failure is blocking!

image: trufflesecurity/trufflehog:3.93.4

clone:
  depth: full

pipelines:
  default:
    - step:
        name: Secret Scan (full)
        script:
          - trufflehog git file://. --results=verified,unknown --fail

  pull-requests:
    '**':
      - step:
          name: Secret Scan (incremental)
          script:
            - trufflehog git file://. --since-commit origin/main --results=verified,unknown --fail
